

#开启debug
debug: false
# logging.level.root
# loggin.file
logging:
  level:
    root: info
  file: /local/user/app-prd.log


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://114.123.11.1:3307/test
    data-username: root
    data-password: root

#自定义属性
mall:
  config:
    name: 优美商城
    description: 这是一家化妆品特卖网站
    hot-sales: 20
    show-advert: true
server:
  port: 80
