#开启debug
debug: true
# logging.level.root
# loggin.file
logging:
 level:
  root: info
 file: E:/myspringboot.log


spring:
 datasource:
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://localhost:3306/test
   data-username: root
   data-password: root

#自定义属性
mall:
 config:
   name: 爱美商城
   description: 这是一家化妆品特卖网站
   hot-sales: 20
   show-advert: true